# Generated by Django 2.2.19 on 2021-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210330_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=96)),
                ('post', models.ManyToManyField(blank=True, related_name='tags', to='blog.Post')),
            ],
        ),
    ]
